### ISSUE TITLE
spaghetti citation?

### ISSUE THREAD

**Issue by jGaboardi** [Robinlovelace/integrating-gat#1]
This looks very interesting, specifically with regards to the [open sources tools](https://github.com/Robinlovelace/integrating-gat#methods-to-identify-open-source-tools)! However, as the lead developer for `spaghetti`, I would disagree that there is [no citation](https://github.com/pysal/spaghetti#bibtex-citation) available.

**Comment by Robinlovelace** [comment]
Thanks @jGaboardi, please point me to the citation. In fact, is this it?:

(Gaboardi et al., 2018)

**Comment by jGaboardi** [comment]
> Thanks @jGaboardi, please point me to the citation. In fact, is this it?:
> 
> (Gaboardi et al., 2018)

Yep! It's linked in my issue above! It's on `spaghetti`'s GitHub README --> https://github.com/pysal/spaghetti#bibtex-citation

**Comment by Robinlovelace** [comment]
Fantastic, it's really important to give software developers the credit they deserve. This is one of the issues I want to raise in the conclusions: it's still not common practice to cite software so hopefully this paper will encourage best practice. 

Any other comments you have on the paper please let me know.

I'll update the README asap. 

In the meantime any other tools you know of here just let me know: https://github.com/Robinlovelace/integrating-gat/blob/master/open_tools.csv

**Comment by jGaboardi** [comment]
Absolutely! I will keep up with this paper and chime in if there are more packages I come across. In general, it seems like the suggestions from your twitter feed are going great! 😆

**Comment by jGaboardi** [comment]
One final comment here. I am working on a [JOSS](https://joss.theoj.org) paper for `spaghetti`. Once that is out the door I will ping here again with that citation info.

**Comment by Robinlovelace** [comment]
Great to hear. I've just updated the README. Please double check it's in there OK and let me know if you have any further comments, great example of benefits of writing not only software but also papers in the open :rocket:

**Comment by jGaboardi** [comment]
This is excellent! I feel very validated! LOL
